### ISSUE TITLE
pepquery implentation error

### ISSUE THREAD

**Issue by chaeyeonk** [bzhanglab/PepQuery#1]
I ran pepquery stand-alone version and got this error (same in linux and windows system).
How can I resolve this problem?

Exception in thread "main" java.sql.SQLException: The database has been closed
        at org.sqlite.core.NativeDB.throwex(NativeDB.java:471)
        at org.sqlite.core.NativeDB.errmsg_utf8(Native Method)
        at org.sqlite.core.NativeDB.errmsg(NativeDB.java:137)
        at org.sqlite.core.DB.newSQLException(DB.java:921)
        at org.sqlite.core.DB.throwex(DB.java:886)
        at org.sqlite.core.NativeDB._open_utf8(Native Method)
        at org.sqlite.core.NativeDB._open(NativeDB.java:71)
        at org.sqlite.core.DB.open(DB.java:174)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:270)
        at main.java.pg.SpectraInput.readMSMSdb(SpectraInput.java:358)
        at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:336)

**Comment by wenbostar** [comment]
Could you please tell me the command line?

**Comment by chaeyeonk** [comment]
>java -jar pepquery.jar -pep ./ref/peptides_unique.txt -db ./ref/nextprot.fasta -fixMod 6 -varMod 107 -um -o ./out -prefix testsearch -tol 20 -tolu ppm -itol 0.5 -cpu 2 -ms ./MS

**Comment by wenbostar** [comment]
Please give a single MGF file to parameter "-ms". If you have multiple MGF files in folder "./MS", you can merge them into one MGF file.

**Comment by chaeyeonk** [comment]
Problem solved. Wenbostar thank you for your kind support! :)
