### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by Missxiang** [bzhanglab/PepQuery#13]
I have meet some problem with indexed database.The command to run is as follows.Start indexing fasta file 50% has an error.
Looking forward to your reply,thanks
```
java -jar ./PepQuery_v1.3.0/pepquery-1.3.jar -pep EGGGGQPPARPATPSGR -db /hwfssz1/ST_CANCER/POL/SHARE/DataBase/Ensembl/Homo_sapiens.GRCh38.pep.all.fa -ms ./pwiz/TCGA_AO-A12D-01A_C8-A131-01A_AO-A12B-01A_Proteome_BI_20130208_MGF/TCGA_AO-A12D_C8-A131_AO-A12B_117C_W_BI_20130208_H-PM_f01.mgf
2019-10-19 16:53:45 [ INFO] Start analysis
2019-10-19 16:53:45 [DEBUG] -pep EGGGGQPPARPATPSGR -db /hwfssz1/ST_CANCER/POL/SHARE/DataBase/Ensembl/Homo_sapiens.GRCh38.pep.all.fa -ms ./pwiz/TCGA_AO-A12D-01A_C8-A131-01A_AO-A12B-01A_Proteome_BI_20130208_MGF/TCGA_AO-A12D_C8-A131_AO-A12B_117C_W_BI_20130208_H-PM_f01.mgf
#############################################
PepQuery parameter:
Fixed modification: 6 = Carbamidomethylation of C
Variable modification: 117 = Oxidation of M
Max allowed variable modification: 3
Add AA substitution: false
Enzyme: 1
Max Missed cleavages: 2
Precursor mass tolerance: 10.0
Precursor ion mass tolerance unit: ppm
Fragment ion mass tolerance: 0.6
Fragment ion mass tolerance unit: Da
Scoring algorithm: 1 = Hyperscore
Min score: 12.0
Min peaks: 10
Min peptide length: 7
Max peptide length: 45
Min peptide mass: 500.0
Max peptide mass: 10000.0
Random peptide number: 10000
CPU: 6
#############################################
Input peptide sequences:1
Don't find indexed database:/hwfssz1/ST_CANCER/POL/SHARE/DataBase/Ensembl/Homo_sapiens.GRCh38.pep.all.fa.sqldb
Use database:/hwfssz1/ST_CANCER/POL/SHARE/DataBase/Ensembl/Homo_sapiens.GRCh38.pep.all.fa
Load db file: /hwfssz1/ST_CANCER/POL/SHARE/DataBase/Ensembl/Homo_sapiens.GRCh38.pep.all.fa
Start indexing fasta file
10% 20% 30% 40% 50%Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 268521
        at com.compomics.util.experiment.identification.protein_inference.fm_index.Rank.getRank(Rank.java:145)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:376)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRankRecursive(WaveletTree.java:379)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.getRank(WaveletTree.java:358)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.prepareWaveletTree(WaveletTree.java:212)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.WaveletTree.<init>(WaveletTree.java:157)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.addDataToIndex(FMIndex.java:1335)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.init(FMIndex.java:1118)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.<init>(FMIndex.java:544)
        at main.java.pg.PepMapping.init(PepMapping.java:82)
        at main.java.pg.PepMapping.loadDB(PepMapping.java:48)
        at main.java.pg.InputProcessor.searchRefDB(InputProcessor.java:400)
        at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:332)
```

**Comment by Missxiang** [comment]
I made reference protein database truncated(only small part),and the command has sucesssfully run.But why I cannot using the complete reference protein database.

**Comment by wenbostar** [comment]
This was caused by the “*” char in protein sequences in your input reference database: Homo_sapiens.GRCh38.pep.all.fa. You can pre-process those sequences who contain “*” by keeping the longest part with splitting the sequences with “*”.

**Comment by Missxiang** [comment]
> This was caused by the ‘*’ char in protein sequences in your input reference database: Homo_sapiens.GRCh38.pep.all.fa. You can pre-process those sequences who contain ‘*’ by keeping the longest part with splitting the sequences with “*”.
If I keep the longest part with splitting the sequences with “*”.Won't the reference database  loss some peptide information?

**Comment by wenbostar** [comment]
I don't think that has big impact on the result. There are only a small fraction of proteins containing "\*" in that database. You can also split these sequences by "\*" and keep all the peptides as different entries in a new fasta file.

**Comment by Missxiang** [comment]
You are right,thank you for your reply!
But I have meet another problems, I want to  search multiple MS/MS datasets using PepQuery in single run.I have downloaded the tool : search_multiple_datasets.py.The -c command require a json  file contains parameters for each MS/MS dataset.The example json file link has invalid.I get this:
`You don't have permission to access /data/msdatasets.json on this server.`
So I don't know the json file format.Could you help me?

**Comment by wenbostar** [comment]
Can you open a new issue for this?

**Comment by wenbostar** [comment]
Do you still have questions about searching multiple datasets? If not, I will close this issue. Thanks.

**Comment by Missxiang** [comment]
I have no question about searching multiple datasets now.You can close this issue.Thank you.
