### ISSUE TITLE
The input file cannot be recognized:No amino acid found for letter

### ISSUE THREAD

**Issue by a1172260832** [bzhanglab/PepQuery#52]
Dear PepQuery2 developers,

I entered a .txt file, but the following error appears: 

Exception in thread "main" java.lang.IllegalArgumentException: No amino acid found for letter ..
        at com.compomics.util.experiment.biology.aminoacids.AminoAcid.getAminoAcid(AminoAcid.java:274)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.createPeptideCombinations(FMIndex.java:1645)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.getProteinMappingWithoutVariants(FMIndex.java:1819)
        at com.compomics.util.experiment.identification.protein_inference.fm_index.FMIndex.getProteinMapping(FMIndex.java:1796)
        at main.java.pg.PepMapping.hasProtein(PepMapping.java:101)
        at main.java.pg.InputProcessor.searchRefDB(InputProcessor.java:421)
        at main.java.pg.PeptideSearchMT.search(PeptideSearchMT.java:337)
        at main.java.pg.PeptideSearchMT.search_multiple_datasets(PeptideSearchMT.java:738)
        at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:183)
        at main.java.pg.IMain.main(IMain.java:30)

My file is in this format(more than 1000 rows): 

MRDPVSSQYSSFLFWRMPIPELDLSELEGLGLSDTATYKVKDSSVGKMIGQATAADQEKNPEGDGLLEYSTFNFWRAPIASIHSFELDLL
MYQGFWSEADVTRPFVSQAVITDGKYFSFFCYQLNTLALTTQADQNNPRKNICWGTQSKPLYETIEDNDVKGFNDDVLLQIVHFLLNRPKEEKSQLLEN
MNAIVALCHFCELHGPRTLFCTEVLHAPLPQGDGNEDSPGQGEQAEEEEAASLQVPPAHEAGPGCPFFPHAGLARSHGEPGDLEKQRRGPRPVSF

Thanks for your help!

**Comment by wenbostar** [comment]
Could you share your complete command line and your fasta file for parameter "-db" here?

**Comment by a1172260832** [comment]
> Could you share your complete command line and your fasta file for parameter "-db" here?

java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b w -db gencode:human -hc -o output -i 
/drives/e/Project/data/convertfa/test.txt

[test.txt](https://github.com/bzhanglab/PepQuery/files/12307989/test.txt)

**Comment by wenbostar** [comment]
I can run the command line with your input without any error. Could you please check your original input peptide file to see if there is any non amino acid string?

In addition, if your sequences in the file are protein sequences, you should add ["-t protein"](http://pepquery.org/document.html#saparameter) to your command line.

**Comment by a1172260832** [comment]
> I can run the command line with your input without any error. Could you please check your original input peptide file to see if there is any non amino acid string?
> 
> In addition, if your sequences in the file are protein sequences, you should add ["-t protein"](http://pepquery.org/document.html#saparameter) to your command line.

I checked the test.txt file, and then I tried it again, but I still had the problem.
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b w -db gencode:human -hc -o output -i /drives/e/Project/data/convertfa/test.txt -t protein > test.log
[test.log](https://github.com/bzhanglab/PepQuery/files/12308893/test.log)


then I move the test.txt to current path, the new error are as follows:

net.sf.kerner.utils.exception.ExceptionFileFormat: failed to get header from MRDPVSSQYSSFLFWRMPIPELDLSELEGLGLSDTATYKVKDSSVGKMIGQATAADQEKNPEGDGLLEYST
FNFWRAPIASIHSFELDLL
        at net.sf.jfasta.impl.FASTAElementHeaderReader.read(FASTAElementHeaderReader.java:76)
        at net.sf.jfasta.impl.FASTAElementIterator.doRead(FASTAElementIterator.java:104)
        at net.sf.jfasta.impl.FASTAElementIterator.doRead(FASTAElementIterator.java:50)
        at net.sf.kerner.utils.io.buffered.AbstractIOIterator.peek(AbstractIOIterator.java:103)
        at net.sf.kerner.utils.io.buffered.AbstractIOIterator.hasNext(AbstractIOIterator.java:109)
        at main.java.pg.InputProcessor.digest(InputProcessor.java:329)
        at main.java.pg.InputProcessor.run(InputProcessor.java:155)
        at main.java.pg.PeptideSearchMT.search(PeptideSearchMT.java:388)
        at main.java.pg.PeptideSearchMT.search_multiple_datasets(PeptideSearchMT.java:738)
        at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:183)
        at main.java.pg.IMain.main(IMain.java:30)

so I removed the "-t protein"
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b w -db gencode:human -hc -o output -i test.txt > test2.log

[test2.log](https://github.com/bzhanglab/PepQuery/files/12309125/test2.log)

Are the warnings in this file normal?

**Comment by wenbostar** [comment]
I don't see any error from the test2.log file. The issue for the test.log is that you have to put your protein sequences to a fasta format file to make it work. In your case, since your input sequences are protein sequences not peptides, you cannot remove -t protein otherwise these sequences will be treated as peptide sequences.

**Comment by wenbostar** [comment]
You could try this:
```shell
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b w -db gencode:human -hc -o output -i MRDPVSSQYSSFLFWRMPIPELDLSELEGLGLSDTATYKVKDSSVGKMIGQATAADQEKNPEGDGLLEYSTFNFWRAPIASIHSFELDLL -t protein
```
In this case, it tries to identify peptides from the protein sequences given to "-i". If you put protein sequences into a file, the file has to be a fasta format file.

**Comment by a1172260832** [comment]
Thank you so much. 
I have other questions: What do you mean by peptide? Is it an independent peptide or part of a protein? If my goal is to verify that this peptide exists and functions independently, does the input parameter also require this "-t protein"?

**Comment by a1172260832** [comment]
It worked! Thank you for your patience!!!

Best wishes~
