### ISSUE TITLE
pepquery error searching for one peptide

### ISSUE THREAD

**Issue by quasarbeam** [bzhanglab/PepQuery#6]
I ran the stand-alone version of Pepquery. As a test, I modified the iPRG one peptide search example for human as follows:
java -jar -Xmx2G ../pepquery.jar -db vcf/Ref_Hsapiens_GRCh37/hg19_refGenePro.fa -fixMod 6 -varMod 107,142,143,15 -maxVar 3 -cpu 4 -fragmentMethod 1 -itol 0.02 -tol 10 -ms vcf/TCGA-A6-3807-01A_f0106.mgf -pep AVVQDPALKPLALVYGEATSR -m 1 -minScore 10 -n 1000 -um -o out

How can I resolve the following error:
PSMs need to map to reference database:0

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at main.java.pg.DatabaseInput.prepareSpectrumForPeptideSearch(DatabaseInput.java:541)
	at main.java.pg.DatabaseInput.readDB(DatabaseInput.java:324)
	at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:461)

**Comment by wenbostar** [comment]
There is no match for this peptide so you got this error. We released a [new version](http://pepquery.org/download.html) in which we have fixed this problem.

**Comment by quasarbeam** [comment]
The new version worked well indeed. Thank you!
BTW, run_input_vcf.sh in the example folder produces the following message on MacOS:

IQuant don't support current System! Only Linux and Windows are supported!

Do you intend to support this feature on MacOS in future release?

**Comment by wenbostar** [comment]
Please try this version: [PepQuery](http://pepquery.org/download.html). It should work well on MacOS.
