### ISSUE TITLE
S3Interface Error when retrieving MS/MS index file!

### ISSUE THREAD

**Issue by TaboneOlivier** [bzhanglab/PepQuery#71]
Dear pepquery developers,

When I try to run the following demo command on a cluster, I got a aws S3 403 error Forbidden when it tries to get the indexed pepqueryDB file probably stored in an aws s3 bucket. 
The following command works on my local computer, and also worked 2 days ago on the same cluster.
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b CPTAC_LUAD_Discovery_Study_Proteome_PDC000153 -db gencode:human -hc -o pepquery_kras_g12d/ -i LVVVGADGVGK

2024-09-11 12:02:29 [INFO ] main.java.pg.PeptideSearchMT[search:250] - Spectrum ID type:1, use 1-based number as index for a spectrum.
2024-09-11 12:02:29 [INFO ] main.java.pg.PeptideSearchMT[search:253] - Step 1: target peptide sequence preparation and initial filtering ...
2024-09-11 12:02:29 [INFO ] main.java.pg.PeptideSearchMT[search:330] - Input peptide sequences:1
2024-09-11 12:02:29 [INFO ] main.java.pg.InputProcessor[searchRefDB:413] - Don't find indexed database:pepquery_kras_g12d//database/gencode.v46.pc_translations_format.fasta.sqldb
2024-09-11 12:02:29 [INFO ] main.java.pg.InputProcessor[searchRefDB:414] - Use database:pepquery_kras_g12d//database/gencode.v46.pc_translations_format.fasta
2024-09-11 12:02:29 [INFO ] main.java.pg.PepMapping[init:62] - Load db file: pepquery_kras_g12d//database/gencode.v46.pc_translations_format.fasta
2024-09-11 12:02:29 [INFO ] main.java.pg.PepMapping[init:78] - Start indexing fasta file
2024-09-11 12:02:34 [INFO ] main.java.pg.PepMapping[init:88] - Indexing took 0.496885216 seconds and consumes 141.36888 MB
2024-09-11 12:02:34 [INFO ] main.java.pg.PeptideSearchMT[search:407] - Valid target peptides: 1
2024-09-11 12:02:34 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1330] - Generate peptide objects ...
2024-09-11 12:02:34 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1341] - CPU: 1
2024-09-11 12:02:34 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1359] - Generate peptide objects done.
2024-09-11 12:02:34 [INFO ] main.java.pg.PeptideSearchMT[search:413] - Step 1: target peptide sequence preparation and initial filtering done: time elapsed = 0.21 min
2024-09-11 12:02:34 [INFO ] main.java.pg.PeptideSearchMT[search:418] - Step 2: candidate spectra retrieval and PSM scoring ...
2024-09-11 12:02:34 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:87] - Used CPUs: 1
2024-09-11 12:02:34 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:88] - Download 1 index MS/MS files ...
2024-09-11 12:02:35 [ERROR] main.java.pg.S3Interface[download:65] - Error when retrieving MS/MS index file!
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 70B4828J5Z10J7C1; S3 Extended Request ID: n9SuHebWl6DEjMUK2v1xRBggUQpqOL7rCoUCaKIN1XNTuCVXcttufJJdXUzXax+jvWJMsSwDtsLKNPu7ddwYfg==; Proxy: null), S3 Extended Request ID: n9SuHebWl6DEjMUK2v1xRBggUQpqOL7rCoUCaKIN1XNTuCVXcttufJJdXUzXax+jvWJMsSwDtsLKNPu7ddwYfg==
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346)
        at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1427)
        at main.java.pg.S3Interface.download(S3Interface.java:54)
        at main.java.msio.IndexFileDownloadWorker.download(IndexFileDownloadWorker.java:34)
        at main.java.msio.IndexFileDownloadWorker.run(IndexFileDownloadWorker.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

Any idea what may cause this error and how to solve it ?
Many thanks for your help,

**Comment by wenbostar** [comment]
I just did a test on my local computer and it works well. The error might be just due to a temporary network connection issue.

**Comment by TaboneOlivier** [comment]
Indeed today it works also on both my local computer and cluster. Thank you for your quick answer and your nice tool.

**Comment by TaboneOlivier** [comment]
Please could you check issue #78 ? This is not a web application issue, but problem in accessing indexed MS files stored in S3 bucket.
Many thanks for your help solving the issue

**Comment by wenbostar** [comment]
We have fixed the data accessing issue. Could you please try again?

**Comment by TaboneOlivier** [comment]
It works again, thanks.
