### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: For input string: "peptide"

### ISSUE THREAD

**Issue by Seb-Leb** [bzhanglab/PepQuery#77]
I am getting an error that I dont understand, could you advise? The input search is a list of peptide and spectrum scan numbers separated by a tab character... (I tried to add "controllerType=0 controllerNumber=1 scan=" in front of the scan number to match the spectrum title, but it gave the same error...) thank you!

PepQuery command:
`-itol 0.05 -hc TRUE -cpu 4 -t peptide -i query_file.txt -e 1 -varMod 117 -maxVar 3 -db tools/uniprot_swissprot_human_2016.fasta -ms spectra.mgf -o outdir`

query file:
```
GREDGELEEGELEDDGAEETQDTSGGPER	12095
NDDIPEQDSLGLSNLQK	17936
MAVAMVK	12715
ATDGMGEGKTAGLGASDCGRAGR	20163
```

Spectra file:
```
>head spectra.mgf
BEGIN IONS
TITLE=controllerType=0 controllerNumber=1 scan=3
SCANS=3
RTINSECONDS=0.895778864
PEPMASS=832.240417480469
CHARGE=2+
122.2260666 4.0869851112
122.9780350 1.9533622265
124.1365204 1.9854439497
144.0026703 7.8467755318
```

output:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "peptide"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.valueOf(Integer.java:999)
	at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:381)
```

**Comment by wenbostar** [comment]
Could you please try to use spectrum title in the mgf file as the spectrum ID in your `` query_file.txt`` file and add parameter "-indexType 2" as well? If this doesn't work, could you share the three input files with me?

**Comment by Seb-Leb** [comment]
Thank you Bo! I tried with the parameter you sent but it still gives the same error.
Here is the full command I use:
`java -Xmx16g -jar pepquery-2.0.2/pepquery-2.0.2.jar -indexType 2 -itol 0.05 -hc TRUE -cpu 4 -t peptide -i pepq_bug/spectra.mgf  -e 1 -varMod 117 -maxVar 3 -db pepq_bug/uniprot_swissprot_human_2016.fasta -ms pepq_bug/spectra.mgf -o pepq_bug`

I zipped all the relevant files in here:
https://drive.google.com/file/d/1Nbw7b5JuSGGjg8o-QoKuCIejLjGu0YFx/view?usp=sharing

**Comment by Seb-Leb** [comment]
I tried changing the spectrum titles to have only the scan numbers, but it still doesn't work...

**Comment by wenbostar** [comment]
I will look at this issue today and get back to you soon.

**Comment by Seb-Leb** [comment]
excellent! thank you!



Seb

________________________________
