### ISSUE TITLE
Error web application 

### ISSUE THREAD

**Issue by ofleitas** [bzhanglab/PepQuery#78]
Hello 

I am trying to run the pepquery web application and got this error 

Error message: simpleWarning in system(javabin, intern = TRUE): running command 'java -Xmx50G -jar tool/pepquery.jar -cpu 0 -s 1 -db database/gencode_v34_human.fasta -b CPTAC_TCGA_Colon_Cancer_Proteome_PDC000111 -minScore 12 -m 1 -o result/Fri_Oct_25_162649_2024_LKCFTVFSSCLKHLVHKYL/ -n 1000 -hc -plot -fast -i LKCFTVFSSCLKHLVHKYL 1>>result/Fri_Oct_25_162649_2024_LKCFTVFSSCLKHLVHKYL//log.txt 2>>result/Fri_Oct_25_162649_2024_LKCFTVFSSCLKHLVHKYL//log.txt' had status 1
Fri Oct 25 16:26:49 2024[32m2024-10-25 16:26:50 [INFO ] main.java.util.CParameterSet[load_default_parameter_sets:146] - Load 12 parameter sets. [m[32m2024-10-25 16:26:50 [INFO ] main.java.util.MSDataSet[load_default_datasets:147] - Load 48 MS/MS datasets. [m[32m2024-10-25 16:26:50 [INFO ] main.java.pg.PeptideSearchMT[main:180] - The number of MS/MS datasets selected: 1, CPTAC_TCGA_Colon_Cancer_Proteome_PDC000111 [m[32m2024-10-25 16:26:50 [INFO ] main.java.pg.PeptideSearchMT[search_multiple_datasets:732] - Searching MS/MS dataset: CPTAC_TCGA_Colon_Cancer_Proteome_PDC000111. 0 left, 0 finished. [m[32m2024-10-25 16:26:50 [INFO ] main.java.pg.CParameter[updateCParameter:873] - Task type: novel peptide identification [m[32m2024-10-25 16:26:50 [INFO ] uk.ac.ebi.pride.utilities.pridemod.io.unimod.xml.unmarshaller.UnimodUnmarshallerFactory[initializeUnmarshaller:41] - Unmarshaller Initialized [m[32m2024-10-25 16:26:51 [INFO ] main.java.OpenModificationSearch.ModificationDB[importPTMsFromUnimod:355] - All modifications in unimod:1375 [m[32m2024-10-25 16:26:51 [INFO ] main.java.pg.PeptideSearchMT[search:243] - Start analysis [m############################################# PepQuery parameter: [32m2024-10-25 16:26:51 [INFO ] main.java.pg.DatabaseInput[getEnzymeByIndex:263] - Use enzyme:Trypsin [mPepQuery version: 2.0.2 PepQuery command line: -cpu 0 -s 1 -db database/gencode_v34_human.fasta -b CPTAC_TCGA_Colon_Cancer_Proteome_PDC000111 -minScore 12 -m 1 -o result/Fri_Oct_25_162649_2024_LKCFTVFSSCLKHLVHKYL/ -n 1000 -hc -plot -fast -i LKCFTVFSSCLKHLVHKYL Fixed modification: 1 = Carbamidomethylation of C Variable modification: 2 = Oxidation of M Max allowed variable modification: 3 Add AA substitution: false Enzyme: 1 = Trypsin Max Missed cleavages: 1 Precursor mass tolerance: 20.0 Range of allowed isotope peak errors: 0 Precursor ion mass tolerance unit: ppm Fragment ion mass tolerance: 0.6 Fragment ion mass tolerance unit: Da Scoring algorithm: 1 = Hyperscore Min score: 12.0 Min peaks: 10 Min peptide length: 7 Max peptide length: 45 Min peptide mass: 500.0 Max peptide mass: 10000.0 Random peptide number: 1000 Fast mode: true CPU: 16 ############################################# [32m2024-10-25 16:26:51 [INFO ] main.java.pg.PeptideSearchMT[search:250] - Spectrum ID type:1, use 1-based number as index for a spectrum. [m[32m2024-10-25 16:26:51 [INFO ] main.java.pg.PeptideSearchMT[search:253] - Step 1: target peptide sequence preparation and initial filtering ... [m[32m2024-10-25 16:26:51 [INFO ] main.java.pg.PeptideSearchMT[search:330] - Input peptide sequences:1 [m[32m2024-10-25 16:26:51 [INFO ] main.java.pg.InputProcessor[searchRefDB:413] - Don't find indexed database:database/gencode_v34_human.fasta.sqldb [m[32m2024-10-25 16:26:51 [INFO ] main.java.pg.InputProcessor[searchRefDB:414] - Use database:database/gencode_v34_human.fasta [m[32m2024-10-25 16:26:51 [INFO ] main.java.pg.PepMapping[init:62] - Load db file: database/gencode_v34_human.fasta [m[32m2024-10-25 16:26:51 [INFO ] main.java.pg.PepMapping[init:78] - Start indexing fasta file [m[32m2024-10-25 16:26:54 [INFO ] main.java.pg.PepMapping[init:88] - Indexing took 0.600355907 seconds and consumes 76.949512 MB [m[32m2024-10-25 16:26:54 [INFO ] main.java.pg.PeptideSearchMT[search:407] - Valid target peptides: 1 [m[32m2024-10-25 16:26:54 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1330] - Generate peptide objects ... [m[32m2024-10-25 16:26:54 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1341] - CPU: 1 [m[32m2024-10-25 16:26:54 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1359] - Generate peptide objects done. [m[32m2024-10-25 16:26:54 [INFO ] main.java.pg.PeptideSearchMT[search:413] - Step 1: target peptide sequence preparation and initial filtering done: time elapsed = 0.08 min [m[32m2024-10-25 16:26:54 [INFO ] main.java.pg.PeptideSearchMT[search:418] - Step 2: candidate spectra retrieval and PSM scoring ... [m[32m2024-10-25 16:26:55 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:87] - Used CPUs: 2 [m[32m2024-10-25 16:26:55 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:88] - Download 2 index MS/MS files ... [m[1;31m2024-10-25 16:26:55 [ERROR] main.java.pg.S3Interface[download:65] - Error when retrieving MS/MS index file! [m[1;31m2024-10-25 16:26:55 [ERROR] main.java.pg.S3Interface[download:65] - Error when retrieving MS/MS index file! [mcom.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: X5GP1YF8YVHFDSP2; S3 Extended Request ID: Lnz37ufho8C9lCV9qoPB3jLp44SbbQ6JlXV/PyGbLgVOjPeaIdlqWYOtX1SacMM4JrIIxwa9F4I=; Proxy: null), S3 Extended Request ID: Lnz37ufho8C9lCV9qoPB3jLp44SbbQ6JlXV/PyGbLgVOjPeaIdlqWYOtX1SacMM4JrIIxwa9F4I= at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372) at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346) at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1427) at main.java.pg.S3Interface.download(S3Interface.java:54) at main.java.msio.IndexFileDownloadWorker.download(IndexFileDownloadWorker.java:34) at main.java.msio.IndexFileDownloadWorker.run(IndexFileDownloadWorker.java:23) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750) com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: X5GPX988WCC6BDV3; S3 Extended Request ID: 6Ne7k+94gJJJAn3jflSoE4pfbzuBJ4/Uuv0ay/GJ4J32gFKrwtgixB077FjGyVYfMNw5AmYmLm4=; Proxy: null), S3 Extended Request ID: 6Ne7k+94gJJJAn3jflSoE4pfbzuBJ4/Uuv0ay/GJ4J32gFKrwtgixB077FjGyVYfMNw5AmYmLm4= at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456) at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403) at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372) at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346) at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1427) at main.java.pg.S3Interface.download(S3Interface.java:54) at main.java.msio.IndexFileDownloadWorker.download(IndexFileDownloadWorker.java:34) at main.java.msio.IndexFileDownloadWorker.run(IndexFileDownloadWorker.java:23) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750)

**Comment by ofleitas** [comment]
Hello 

I also tried the standalone version I got his error and 

PS C:\Users\ofm83\OneDrive\Documents\pepquery> java -jar C:\Users\ofm83\OneDrive\Documents\pepquery-2.0.2\pepquery-2.0.2.jar -b  Academia_Sinica_LUAD100_Phosphoproteome_PDC000220 -db gencode:human -hc -s 1 -o .\gencode\1\ -i LVVVGADGVGK                                                                                                                                                                      
2024-10-27 14:21:20 [INFO ] main.java.util.CParameterSet[load_default_parameter_sets:146] - Load 12 parameter sets.
2024-10-27 14:21:20 [INFO ] main.java.util.MSDataSet[load_default_datasets:147] - Load 48 MS/MS datasets.
2024-10-27 14:21:20 [INFO ] main.java.pg.PeptideSearchMT[main:180] - The number of MS/MS datasets selected: 1, Academia_Sinica_LUAD100_Phosphoproteome_PDC000220
2024-10-27 14:21:20 [INFO ] main.java.pg.PeptideSearchMT[search_multiple_datasets:732] - Searching MS/MS dataset: Academia_Sinica_LUAD100_Phosphoproteome_PDC000220. 0 left, 0 finished.
2024-10-27 14:21:23 [INFO ] main.java.download.FileDownload[download_single_file:523] - Download file ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/gencode.v47.pc_translations.fa.gz to .\gencode\1\\database\gencode.v47.pc_translations.fa.gz
2024-10-27 14:21:30 [INFO ] main.java.download.FileDownload[download_single_file:531] - Download file ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/gencode.v47.pc_translations.fa.gz to .\gencode\1\\database\gencode.v47.pc_translations.fa.gz done
2024-10-27 14:21:35 [INFO ] main.java.pg.CParameter[updateCParameter:873] - Task type: novel peptide identification
2024-10-27 14:21:36 [INFO ] uk.ac.ebi.pride.utilities.pridemod.io.unimod.xml.unmarshaller.UnimodUnmarshallerFactory[initializeUnmarshaller:41] - Unmarshaller Initialized
2024-10-27 14:21:36 [INFO ] main.java.OpenModificationSearch.ModificationDB[importPTMsFromUnimod:355] - All modifications in unimod:1375
2024-10-27 14:21:36 [INFO ] main.java.pg.PeptideSearchMT[search:243] - Start analysis
#############################################
PepQuery parameter:
2024-10-27 14:21:36 [INFO ] main.java.pg.DatabaseInput[getEnzymeByIndex:263] - Use enzyme:Trypsin
PepQuery version: 2.0.2
PepQuery command line: -b Academia_Sinica_LUAD100_Phosphoproteome_PDC000220 -db gencode:human -hc -s 1 -o .\gencode\1\ -i LVVVGADGVGK
Fixed modification: 1,11,12 = Carbamidomethylation of C,TMT 10-plex of K,TMT 10-plex of peptide N-term
Variable modification: 2,7,8,9 = Oxidation of M,Phosphorylation of S,Phosphorylation of T,Phosphorylation of Y
Max allowed variable modification: 3
Add AA substitution: false
Enzyme: 1 = Trypsin
Max Missed cleavages: 1
Precursor mass tolerance: 20.0
Range of allowed isotope peak errors: 0
Precursor ion mass tolerance unit: ppm
Fragment ion mass tolerance: 0.05
Fragment ion mass tolerance unit: Da
Scoring algorithm: 1 = Hyperscore
Min score: 12.0
Min peaks: 10
Min peptide length: 7
Max peptide length: 45
Min peptide mass: 500.0
Max peptide mass: 10000.0
Random peptide number: 10000
Fast mode: false
CPU: 16
#############################################
2024-10-27 14:21:36 [INFO ] main.java.pg.PeptideSearchMT[search:250] - Spectrum ID type:1, use 1-based number as index for a spectrum.
2024-10-27 14:21:36 [INFO ] main.java.pg.PeptideSearchMT[search:253] - Step 1: target peptide sequence preparation and initial filtering ...
2024-10-27 14:21:36 [INFO ] main.java.pg.PeptideSearchMT[search:330] - Input peptide sequences:1
2024-10-27 14:21:36 [INFO ] main.java.pg.InputProcessor[searchRefDB:413] - Don't find indexed database:.\gencode\1\\database\gencode.v47.pc_translations_format.fasta.sqldb
2024-10-27 14:21:36 [INFO ] main.java.pg.InputProcessor[searchRefDB:414] - Use database:.\gencode\1\\database\gencode.v47.pc_translations_format.fasta
2024-10-27 14:21:36 [INFO ] main.java.pg.PepMapping[init:62] - Load db file: .\gencode\1\\database\gencode.v47.pc_translations_format.fasta
2024-10-27 14:21:36 [INFO ] main.java.pg.PepMapping[init:78] - Start indexing fasta file
2024-10-27 14:22:06 [INFO ] main.java.pg.PepMapping[init:88] - Indexing took 27.5166925 seconds and consumes 141.813152 MB
2024-10-27 14:22:06 [INFO ] main.java.pg.PeptideSearchMT[search:407] - Valid target peptides: 1
2024-10-27 14:22:06 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1330] - Generate peptide objects ...
2024-10-27 14:22:06 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1341] - CPU: 1
2024-10-27 14:22:06 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1359] - Generate peptide objects done.
2024-10-27 14:22:06 [INFO ] main.java.pg.PeptideSearchMT[search:413] - Step 1: target peptide sequence preparation and initial filtering done: time elapsed = 0.78 min
2024-10-27 14:22:06 [INFO ] main.java.pg.PeptideSearchMT[search:418] - Step 2: candidate spectra retrieval and PSM scoring ...
2024-10-27 14:22:07 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:87] - Used CPUs: 1
2024-10-27 14:22:07 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:88] - Download 1 index MS/MS files ...
2024-10-27 14:22:08 [ERROR] main.java.pg.S3Interface[download:65] - Error when retrieving MS/MS index file!
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: J3KV99JPFK5WFSSX; S3 Extended Request ID: 0PaEitKMKBimUMRo86gAOiQLo1jxWqecVAs6IaXlrUSxpas9flF0bjnDEGnjKuVBeMSg7jgvnNHzEjE3bMTNUg==; Proxy: null), S3 Extended Request ID: 0PaEitKMKBimUMRo86gAOiQLo1jxWqecVAs6IaXlrUSxpas9flF0bjnDEGnjKuVBeMSg7jgvnNHzEjE3bMTNUg==     
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346)
        at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1427)
        at main.java.pg.S3Interface.download(S3Interface.java:54)
        at main.java.msio.IndexFileDownloadWorker.download(IndexFileDownloadWorker.java:34)
        at main.java.msio.IndexFileDownloadWorker.run(IndexFileDownloadWorker.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
PS C:\Users\ofm83\OneDrive\Documents\pepquery>

**Comment by pixuenan** [comment]
Cannot access the aws object in the command line java standalone neither.
My current location is at ChengDu.
The pepquery web works fine.
The error message is as following:
```
2024-10-31 15:19:16 [ERROR] main.java.pg.S3Interface[download:65] - Error when retrieving MS/MS index file!
2024-10-31 15:19:16 [ERROR] main.java.pg.S3Interface[download:65] - Error when retrieving MS/MS index file!
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: YEC5T0NTXTVVEE1D; S3 Extended Request ID: zIxnbT6Ti9lax1vmgcDwc/v9sNia18SqULEbN1NzhXgMxAwxFEWt3IxpDHhAsQ6XLemoKLX4lrk=; Proxy: null), S3 Extended Request ID: zIxnbT6Ti9lax1vmgcDwc/v9sNia18SqULEbN1NzhXgMxAwxFEWt3IxpDHhAsQ6XLemoKLX4lrk=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346)
        at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1427)
        at main.java.pg.S3Interface.download(S3Interface.java:54)
        at main.java.msio.IndexFileDownloadWorker.download(IndexFileDownloadWorker.java:34)
        at main.java.msio.IndexFileDownloadWorker.run(IndexFileDownloadWorker.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by TaboneOlivier** [comment]
Hi, I also have the same issue. I cannot use pepquery db datasets for 10 days.
This throws the same error I've already got (issue #71 ).
Any clue on how to solve it? Is it related to aws cloud side?
Thank you for your help,

**Comment by wenbostar** [comment]
We have fixed the data accessing issue. Could you please try again?

**Comment by ofleitas** [comment]
Hello 

It is working for me.
Thank you very much !!
