### ISSUE TITLE
Error reading thermoraw file

### ISSUE THREAD

**Issue by anuC** [bzhanglab/PepQuery#79]
Hi,

While running PepQuery standalone with a thermoraw file, following error occurred. 

> 2024-11-08 11:15:05 [INFO ] main.java.pg.PeptideSearchMT[search:407] - Valid target peptides: 573
2024-11-08 11:15:05 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1330] - Generate peptide objects ...
2024-11-08 11:15:05 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1341] - CPU: 32
2024-11-08 11:15:05 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1359] - Generate peptide objects done.
2024-11-08 11:15:05 [INFO ] main.java.pg.PeptideSearchMT[search:413] - Step 1: target peptide sequence preparation and initial filtering done: time elapsed = 0.08 min
2024-11-08 11:15:05 [INFO ] main.java.pg.PeptideSearchMT[search:418] - Step 2: candidate spectra retrieval and PSM scoring ...
Exception in thread "main" org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.throwex(DB.java:1007)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
        at org.sqlite.core.DB.prepare(DB.java:257)
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
        at main.java.pg.SpectraInput.readMSMSdb2(SpectraInput.java:285)
        at main.java.pg.PeptideSearchMT.search(PeptideSearchMT.java:452)
        at main.java.pg.PeptideSearchMT.main(PeptideSearchMT.java:214)
        at main.java.pg.IMain.main(IMain.java:30)

I am using the following command - 
`java -Xmx30G -jar /pepquery-2.0.2/pepquery-2.0.2.jar -ms P1819.raw -db uniprotkb_organism_id_9606_AND_reviewed_2024_08_19.fasta -hc -s 2 -m 1 -o ITPR3_HUMAN -i "sp|Q14573|ITPR3_HUMAN" -t protein -fast`

The instrument details are - All LC-MS/MS experiments were performed using a Dionex Ultimate 3000 RSLC  nanoUPLC (Thermo Fisher Scientific Inc, Waltham, MA, USA) system and a Q Exactive Orbitrap mass spectrometer (Thermo Fisher Scientific Inc, Waltham, MA, USA)

Any help would be highly appreciated.

Kind regards
Anu

**Comment by wenbostar** [comment]
If input is a .raw file, you also need to set the following parameter for converting the raw to an open format:

```
-dc: Tool path for Raw MS/MS data conversion: for example, /home/test/ThermoRawFileParser/ThermoRawFileParser.exe.
```

It might be easier to just convert the raw to mgf and then run PepQuery on the mgf file.

**Comment by anuC** [comment]
Thank you for the reply!
