### ISSUE TITLE
Issue with Amazon S3 Access Denied Error during PepQuery Execution

### ISSUE THREAD

**Issue by bioyangyang** [bzhanglab/PepQuery#81]
Hello,

I'm encountering a 403 Forbidden error when attempting to download MS/MS index files from Amazon S3 while running PepQuery. Here are the details of my issue:

PepQuery Version: 2.0.2

Command Used: 
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b CPTAC_LUAD_Discovery_Study_Proteome_PDC000153 -db gencode:human -hc -o pepquery_kras_g12d/ -i LVVVGADGVGK

Error Message:
java -jar pepquery-2.0.2/pepquery-2.0.2.jar -b CPTAC_LUAD_Discovery_Study_Proteome_PDC000153 -db gencode:human -hc -o pepquery_kras_g12d/ -i LVVVGADGVGK
2024-11-25 14:25:40 [INFO ] main.java.util.CParameterSet[load_default_parameter_sets:146] - Load 12 parameter sets.
2024-11-25 14:25:40 [INFO ] main.java.util.MSDataSet[load_default_datasets:147] - Load 48 MS/MS datasets.
2024-11-25 14:25:40 [INFO ] main.java.pg.PeptideSearchMT[main:180] - The number of MS/MS datasets selected: 1, CPTAC_LUAD_Discovery_Study_Proteome_PDC000153
2024-11-25 14:25:40 [INFO ] main.java.pg.PeptideSearchMT[search_multiple_datasets:732] - Searching MS/MS dataset: CPTAC_LUAD_Discovery_Study_Proteome_PDC000153. 0 left, 0 finished.
2024-11-25 14:25:43 [INFO ] main.java.download.FileDownload[download_single_file:523] - Download file ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/gencode.v47.pc_translations.fa.gz to pepquery_kras_g12d//database/gencode.v47.pc_translations.fa.gz
2024-11-25 14:26:14 [INFO ] main.java.download.FileDownload[download_single_file:531] - Download file ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/gencode.v47.pc_translations.fa.gz to pepquery_kras_g12d//database/gencode.v47.pc_translations.fa.gz done
2024-11-25 14:26:17 [INFO ] main.java.pg.CParameter[updateCParameter:873] - Task type: novel peptide identification
2024-11-25 14:26:17 [INFO ] uk.ac.ebi.pride.utilities.pridemod.io.unimod.xml.unmarshaller.UnimodUnmarshallerFactory[initializeUnmarshaller:41] - Unmarshaller Initialized
2024-11-25 14:26:18 [INFO ] main.java.OpenModificationSearch.ModificationDB[importPTMsFromUnimod:355] - All modifications in unimod:1375
2024-11-25 14:26:18 [INFO ] main.java.pg.PeptideSearchMT[search:243] - Start analysis
#############################################
PepQuery parameter:
2024-11-25 14:26:18 [INFO ] main.java.pg.DatabaseInput[getEnzymeByIndex:263] - Use enzyme:Trypsin
PepQuery version: 2.0.2
PepQuery command line: -b CPTAC_LUAD_Discovery_Study_Proteome_PDC000153 -db gencode:human -hc -o pepquery_kras_g12d/ -i LVVVGADGVGK
Fixed modification: 1,11,12 = Carbamidomethylation of C,TMT 10-plex of K,TMT 10-plex of peptide N-term
Variable modification: 2 = Oxidation of M
Max allowed variable modification: 3
Add AA substitution: false
Enzyme: 1 = Trypsin
Max Missed cleavages: 1
Precursor mass tolerance: 20.0
Range of allowed isotope peak errors: 0
Precursor ion mass tolerance unit: ppm
Fragment ion mass tolerance: 0.05
Fragment ion mass tolerance unit: Da
Scoring algorithm: 1 = Hyperscore
Min score: 12.0
Min peaks: 10
Min peptide length: 7
Max peptide length: 45
Min peptide mass: 500.0
Max peptide mass: 10000.0
Random peptide number: 10000
Fast mode: false
CPU: 64
#############################################
2024-11-25 14:26:18 [INFO ] main.java.pg.PeptideSearchMT[search:250] - Spectrum ID type:1, use 1-based number as index for a spectrum.
2024-11-25 14:26:18 [INFO ] main.java.pg.PeptideSearchMT[search:253] - Step 1: target peptide sequence preparation and initial filtering ...
2024-11-25 14:26:18 [INFO ] main.java.pg.PeptideSearchMT[search:330] - Input peptide sequences:1
2024-11-25 14:26:18 [INFO ] main.java.pg.InputProcessor[searchRefDB:413] - Don't find indexed database:pepquery_kras_g12d//database/gencode.v47.pc_translations_format.fasta.sqldb
2024-11-25 14:26:18 [INFO ] main.java.pg.InputProcessor[searchRefDB:414] - Use database:pepquery_kras_g12d//database/gencode.v47.pc_translations_format.fasta
2024-11-25 14:26:18 [INFO ] main.java.pg.PepMapping[init:62] - Load db file: pepquery_kras_g12d//database/gencode.v47.pc_translations_format.fasta
2024-11-25 14:26:18 [INFO ] main.java.pg.PepMapping[init:78] - Start indexing fasta file
2024-11-25 14:26:21 [INFO ] main.java.pg.PepMapping[init:88] - Indexing took 0.425416428 seconds and consumes 141.813152 MB
2024-11-25 14:26:21 [INFO ] main.java.pg.PeptideSearchMT[search:407] - Valid target peptides: 1
2024-11-25 14:26:21 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1330] - Generate peptide objects ...
2024-11-25 14:26:21 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1341] - CPU: 1
2024-11-25 14:26:21 [INFO ] main.java.pg.PeptideSearchMT[generatePeptideInputs:1359] - Generate peptide objects done.
2024-11-25 14:26:21 [INFO ] main.java.pg.PeptideSearchMT[search:413] - Step 1: target peptide sequence preparation and initial filtering done: time elapsed = 0.68 min
2024-11-25 14:26:21 [INFO ] main.java.pg.PeptideSearchMT[search:418] - Step 2: candidate spectra retrieval and PSM scoring ...
2024-11-25 14:26:21 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:87] - Used CPUs: 1
2024-11-25 14:26:21 [INFO ] main.java.msio.MsdataMatch[get_all_indexed_ms_file:88] - Download 1 index MS/MS files ...
2024-11-25 14:26:22 [ERROR] main.java.pg.S3Interface[download:65] - Error when retrieving MS/MS index file!
com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 8DN61CZ3WBHK8FDD; S3 Extended Request ID: E3HkOA2iW2jT+OnhwepYsB2gEPiisPxnqiCLxW759rwI+EWn7rwEu0WtHkk1d9EQpaYoORnCPYI/LD2+DCz8Lg==; Proxy: null), S3 Extended Request ID: E3HkOA2iW2jT+OnhwepYsB2gEPiisPxnqiCLxW759rwI+EWn7rwEu0WtHkk1d9EQpaYoORnCPYI/LD2+DCz8Lg==
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1346)
	at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1427)
	at main.java.pg.S3Interface.download(S3Interface.java:54)
	at main.java.msio.IndexFileDownloadWorker.download(IndexFileDownloadWorker.java:34)
	at main.java.msio.IndexFileDownloadWorker.run(IndexFileDownloadWorker.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I would appreciate any guidance on how to resolve this issue. It seems to be a permissions or configuration problem, but I'm unable to pinpoint the exact cause. Any assistance would be greatly appreciated.

Best regards,
Yang

**Comment by wenbostar** [comment]
We have fixed the data accessing issue. Could you please try again?

**Comment by bioyangyang** [comment]
Yes, it works. Thanks for the quick fix on my issue! Really appreciate your help.
